---
# tasks file for elasticsearch
- name: "Be sure that Elasticsearch GPG Key is installed"
  apt_key:
    id: "D88E42B4"
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: "Be sure to add Elasticsearch repository"
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present
    filename: 'elastic-5.x'

- name: "Be sure to install the elasticsearch package"
  apt:
   name: "elasticsearch"
   state: latest
   update_cache: yes

- name: "Be sure to enable elasticsearch service and ensure it is not masked"
  systemd:
   name: "elasticsearch.service"
   daemon_reload: yes
   enabled: yes
   state: started
   masked: no
